name: CommuteOptimizer
options:
  bundleIdPrefix: com.commuteoptimizer
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

targets:
  CommuteOptimizer:
    type: application
    platform: iOS
    sources:
      - path: CommuteOptimizer
        excludes:
          - "**/*.xcodeproj"
          - "**/*.xcworkspace"
    resources:
      - path: CommuteOptimizer/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.commuteoptimizer.app
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        CODE_SIGN_ENTITLEMENTS: CommuteOptimizer/CommuteOptimizer.entitlements
    entitlements:
      path: CommuteOptimizer/CommuteOptimizer.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.commuteoptimizer
    dependencies:
      - target: CommuteWidgetExtension
        embed: true

  CommuteOptimizerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CommuteOptimizerTests
    dependencies:
      - target: CommuteOptimizer

  CommuteWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: CommuteWidget
      # Widget needs access to shared code
      - path: CommuteOptimizer/Models
      - path: CommuteOptimizer/Services
      - path: CommuteOptimizer/Utilities
    resources:
      - path: CommuteOptimizer/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.commuteoptimizer.app.widget
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: CommuteWidget
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        CODE_SIGN_ENTITLEMENTS: CommuteWidget/CommuteWidget.entitlements
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    entitlements:
      path: CommuteWidget/CommuteWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.commuteoptimizer

schemes:
  CommuteOptimizer:
    build:
      targets:
        CommuteOptimizer: all
        CommuteWidgetExtension: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - CommuteOptimizerTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
