name: CommuteOptimizer
options:
  bundleIdPrefix: com.commuteoptimizer
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

targets:
  CommuteOptimizer:
    type: application
    platform: iOS
    sources:
      - path: CommuteOptimizer
        excludes:
          - "**/*.xcodeproj"
          - "**/*.xcworkspace"
    resources:
      - path: CommuteOptimizer/Resources
      - path: CommuteOptimizer/Assets.xcassets
      - path: CommuteOptimizer/PrivacyInfo.xcprivacy
      - path: CommuteOptimizer/PrivacyInfo.xcprivacy
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.commuteoptimizer.app
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: CommuteOptimizer/Info.plist
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        CODE_SIGN_ENTITLEMENTS: CommuteOptimizer/CommuteOptimizer.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: CommuteOptimizer/CommuteOptimizer.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.commuteoptimizer
    dependencies:
      - target: CommuteWidgetExtension
        embed: true

  CommuteOptimizerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CommuteOptimizerTests
    dependencies:
      - target: CommuteOptimizer

  CommuteWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: CommuteWidget
        excludes:
          - Info.plist
      # Widget needs access to shared code
      - path: CommuteOptimizer/Models
      - path: CommuteOptimizer/Services
      - path: CommuteOptimizer/Utilities
      # Resources must be in sources for widget extensions
      - path: CommuteOptimizer/Resources/stations.json
        type: file
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.commuteoptimizer.app.widget
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_ENTITLEMENTS: CommuteWidget/CommuteWidget.entitlements
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_FILE: CommuteWidget/Info.plist
    entitlements:
      path: CommuteWidget/CommuteWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.commuteoptimizer

schemes:
  CommuteOptimizer:
    build:
      targets:
        CommuteOptimizer: all
        CommuteWidgetExtension: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - CommuteOptimizerTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  CommuteWidgetExtension:
    build:
      targets:
        CommuteWidgetExtension: all
    run:
      config: Debug
